---
apiVersion: v1
kind: Secret
metadata:
  name: ops-manager-organization-apikey-test-project
type: Opaque
stringData:
  # Public Key
  user: RPBMIYVJ
  # Private Key
  publicApiKey: 947f897a-d270-42aa-ae1f-7ce76ba59118
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-manager-test-project-config
data:
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080
  orgId: 61b430bdf925210070409f35
  projectName: test-project
