--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: test-project-svc
    controller: mongodb-enterprise-operator
    statefulset.kubernetes.io/pod-name: test-project-0
  name: test-project-0-svc-ext
  namespace: mongodb
spec: 
  ports: 
    - 
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector: 
    app: test-project-svc
    controller: mongodb-enterprise-operator
    statefulset.kubernetes.io/pod-name: test-project-0
  type: LoadBalancer
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: test-project-svc
    controller: mongodb-enterprise-operator
    statefulset.kubernetes.io/pod-name: test-project-1
  name: test-project-1-svc-ext
  namespace: mongodb
spec: 
  ports: 
    - 
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector: 
    app: test-project-svc
    controller: mongodb-enterprise-operator
    statefulset.kubernetes.io/pod-name: test-project-1
  type: LoadBalancer
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: test-project-svc
    controller: mongodb-enterprise-operator
    statefulset.kubernetes.io/pod-name: test-project-2
  name: test-project-2-svc-ext
  namespace: mongodb
spec: 
  ports: 
    - 
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector: 
    app: test-project-svc
    controller: mongodb-enterprise-operator
    statefulset.kubernetes.io/pod-name: test-project-2
  type: LoadBalancer
