--- 
apiVersion: mongodb.com/v1
kind: MongoDB
metadata: 
  name: test-project
spec: 
  credentials: ops-manager-organization-apikey-test-project
  members: 3
  type: ReplicaSet
  version: 4.2.2-ent
  opsManager: 
    configMapRef: 
      name: ops-manager-test-project-config
  security: 
    authentication: 
      enabled: true
      modes: ["SCRAM","X509"]
    tls: 
      ca: test-project-ca
      enabled: true
